- name: setting locale
  locale_gen:
    name: "{{ system_locale }}"
    state: present
  when: package_manager == "apt"

- name: install epel-release
  package: 
    name: epel-release
    state: present
    use: "{{ package_manager }}"
  when: package_manager == "yum"

- name: install postgresql repo
  package: 
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    use: "{{ package_manager }}"
  when: package_manager == "yum"

- name: install sudo
  package: 
    name: sudo
    state: present
    use: "{{ package_manager }}"

- name: installing dependencies
  package: 
    name: [ "{{ postgresql_package_name }}"]
    state: present
    update_cache: yes
    use: "{{ package_manager }}"
# postgresql-11-postgis-2.5-scripts #for postgis.control
# postgresql-contrib #for dblink extension

- name: install python-psycopg2 for ansible psql modules
  package: 
    name: python-psycopg2
    state: present
    use: "{{ package_manager }}"

- name: init postgresql database
  command: >
    /usr/pgsql-11/bin/postgresql-11-setup initdb
  when: package_manager == "yum"

- name: Test if postgresql is running
  service: 
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: yes

- name: create georchestra user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ georchestra.db.user }}"
    password: "{{ georchestra.db.pass }}"
    encrypted: yes

- name: create georchestra main database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ georchestra.db.name }}"
    owner: "{{ georchestra.db.user }}"
    template: template0
    encoding: UTF8

- include: geonetwork.yml
  become: yes
  become_user: postgres
  tags: postgresql_geonetwork

- include: geofence.yml
  become: yes
  become_user: postgres
  tags: postgresql_geofence

- include: other_schemas.yml
  become: yes
  become_user: postgres
  tags: postgresql_other_schemas

- include: cadastrapp.yml
  tags: postgresql_cadastrapp
  when: cadastrapp.enabled

- include: clean.yml
  tags: [cleanup, postgresql_cleanup]
  when: cleanup is defined
