- name: install the datahub UI
  get_url:
    url: "{{ datahub.url }}"
    dest: "/var/www/georchestra/htdocs/datahub.zip"

- name: unzips the war
  unarchive:
    src: "/var/www/georchestra/htdocs/datahub.zip"
    dest: "/var/www/georchestra/htdocs/"
    remote_src: yes

- name: removes the downloaded archive
  file:
    path: "/var/www/georchestra/htdocs/datahub.zip"
    state: absent

- name: set base url in index.html
  replace:
    path: /var/www/georchestra/htdocs/datahub/index.html
    regexp: '<base href="/">'
    replace: '<base href="/datahub/">'

- name: templatize the apache config for datahub
  template:
    src: "datahub.conf.j2"
    dest: "/var/www/georchestra/conf/datahub.conf"
  notify: reload apache2

- name: custom asset
  copy:
    src: "{{ georchestra.datadir.path }}/datahub/assets/" 
    dest: "/var/www/georchestra/htdocs/datahub/assets/"
    owner: root
    group: root
    mode: '0644'
    remote_src: true

- name: custom configuration
  copy:
    src: "{{ georchestra.datadir.path }}/datahub/conf/" 
    dest: "/var/www/georchestra/htdocs/datahub/assets/configuration/"
    owner: root
    group: root
    mode: '0644'
    remote_src: true