- name: create datadirs
  tags: wars
  file:
    path: "{{ item }}"
    state: directory
    owner: tomcat
    group: tomcat
  with_items:
  - "{{ geonetwork.datadir.path }}"
  - "{{ geoserver.datadir.path }}"
  - "{{ geowebcache_datadir }}"
  - "{{ extractor_datadir }}"

- include: config.yml
  tags: config

- include: keystore.yml
  tags: keystore

- include: sviewer.yml
  tags: sviewer
  when: mviewer.enabled

- include: mviewer.yml
  tags: mviewer
  when: mviewer.enabled

- include: war_cadastrapp.yml
  tags: cadastrapp_war
  when: cadastrapp.enabled

- include: geoserver.yml
  tags: geoserver

- include: geonetwork.yml
  tags: geonetwork

- include: wars.yml
  tags: wars

- include: nativelibs.yml
  tags: nativelibs
  when: package_manager == "apt"

- include: cadastrapp.yml
  tags: cadastrapp_addon
  when: cadastrapp.enabled

- include: clean.yml
  tags: [cleanup, georchestra_cleanup]
  when: cleanup is defined
