- name: create wars folder
  file:
      path: "/usr/share/lib/georchestra/20.0.1"
      state: directory

- name: download wars
  get_url:
    url: "https://packages.georchestra.org/bot/wars/20.0.x/{{ item.key }}-generic.war"
    dest: "/usr/share/lib/georchestra/20.0.1/{{ item.key }}-generic.war"
    validate_certs: false
    force: true
  with_dict: "{{ georchestra_wars }}"
  tags: download

- name: symlink webapps in each tomcat instance
  file:
    owner: tomcat
    src: "/usr/share/lib/georchestra/20.0.1/{{ item.key }}-generic.war"
    dest: "{{ tomcat_basedir }}/{{ item.value.tomcat }}/webapps/{{ item.key }}.war"
    state: link
    force: yes
  with_dict: "{{ georchestra_wars }}"

# instances need to be started so that webapps are deployed
- name: start instances
  service:
    name: "tomcat@{{ item }}"
    state: started
  with_items: "{{ tomcat_instances.keys() }}"

