- name: add adoptopenjdk repository key
  tags: java8
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
  when: package_manager == "apt"  

- name: add adoptopenjdk debian repo
  tags: java8
  apt_repository:
    repo: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main"
  when: package_manager == "apt" 

- name: install java8 from adoptopenjdk
  tags: java8
  apt:
    pkg: adoptopenjdk-8-hotspot
    default_release: buster
    update_cache: yes
    state: latest
  when: package_manager == "apt"   

- name: default to adoptopenjdk
  tags: java8
  alternatives:
    name: java
    path: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java
  when: package_manager == "apt" 

- name: install jdk8
  tags: java8
  alternatives:
    name: java
    path: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java
  when: package_manager == "apt" 

- name: install tomcat dependencies
  package: 
    name: "{{ tomcat_package_name }}"
    state: present
    update_cache: yes
    use: "{{ package_manager }}"

- name: disable default instance
  service:
    name: "{{ tomcat_service_name }}"
    state: stopped
    enabled: no

- name: template tmpfiles.d for pidfile
  tags: systemd_unit
  template:
    src: tomcat.conf.j2
    dest: /etc/tmpfiles.d/tomcat.conf
  register: tomcat_piddir

- name: add fqdn to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ georchestra.fqdn }}"

- name: create temp dir
  tags: systemd_unit
  command: systemd-tmpfiles  --prefix=/run/tomcat --create
  when: tomcat_piddir.changed

- name: template systemd unit
  tags: systemd_unit
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat@.service

- name: reload systemd so that it finds the new unit
  tags: systemd_unit
  systemd:
    daemon-reload: yes
    name: tomcat@.service

- name: disable assistive_technologies (requires non-headless jdk)
  lineinfile:
    dest: /etc/java-8-openjdk/accessibility.properties
    line: 'assistive_technologies=org.GNOME.Accessibility.AtkWrapper'
    state: absent

- name: create tomcat_basedir
  file:
    name: "{{ tomcat_basedir }}"
    state: directory

- name: create common logdir
  file:
    path: "{{ logs_basedir }}"
    state: directory
    owner: tomcat
    group: tomcat
