- include: common.yml
- include: instance.yml
  tags: tomcat-instance
- include: cadastrapp.yml
  when: cadastrapp.enabled
- include: clean.yml
  tags: [cleanup, tomcat_cleanup]
  when: cleanup is defined
